
//----------------------------------------------------
// The following code was generated by CUP v0.11a beta 20060608
// Tue Dec 11 17:37:59 IST 2012
//----------------------------------------------------

package IC.Parser;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int DIVIDE = 32;
  public static final int LCBR = 6;
  public static final int LTE = 22;
  public static final int UMINUS = 34;
  public static final int INTEGER = 12;
  public static final int CONTINUE = 41;
  public static final int SEMI = 10;
  public static final int INT = 15;
  public static final int MINUS = 28;
  public static final int STATIC = 35;
  public static final int LT = 21;
  public static final int LP = 2;
  public static final int COMMA = 8;
  public static final int CLASS = 39;
  public static final int RP = 3;
  public static final int PLUS = 29;
  public static final int MULTIPLY = 30;
  public static final int QUOTE = 48;
  public static final int IF = 36;
  public static final int ASSIGN = 33;
  public static final int THIS = 43;
  public static final int ID = 46;
  public static final int DOT = 9;
  public static final int EOF = 0;
  public static final int BOOLEAN = 11;
  public static final int RETURN = 40;
  public static final int RCBR = 7;
  public static final int LB = 4;
  public static final int LAND = 24;
  public static final int EQUAL = 17;
  public static final int TRUE = 27;
  public static final int NEW = 45;
  public static final int error = 1;
  public static final int RB = 5;
  public static final int LOR = 25;
  public static final int NULL = 16;
  public static final int MOD = 31;
  public static final int BREAK = 38;
  public static final int VOID = 14;
  public static final int GTE = 20;
  public static final int ELSE = 37;
  public static final int WHILE = 44;
  public static final int NEQUAL = 18;
  public static final int CLASS_ID = 47;
  public static final int EXTENDS = 42;
  public static final int STRING = 13;
  public static final int LNEG = 23;
  public static final int FALSE = 26;
  public static final int GT = 19;
  public static final int LENGTH = 49;
}

