package IC.Parser;

public class sym {
  public static final int LP = 1;
  public static final int RP = 2;
  public static final int ASSIGN = 3;
  public static final int BOOLEAN = 4;
  public static final int BREAK = 5;
  public static final int CLASS = 6;
  public static final int COMMA = 7;
  public static final int CONTINUE = 8;
  public static final int DIVIDE = 9;
  public static final int DOT = 10;
  public static final int EQUAL = 11;
  public static final int EXTENDS = 12;
  public static final int ELSE = 13;
  public static final int FALSE = 14;
  public static final int TRUE = 15;
  public static final int GT = 16;
  public static final int GTE = 17;
  public static final int LT = 18;
  public static final int LTE = 19;
  public static final int NEQUAL = 20;
  public static final int ID = 21;
  public static final int IF = 22;
  public static final int MINUS = 23;
  public static final int PLUS = 24;
  public static final int MULTIPLY = 25;
  public static final int CLASS_ID = 26;
  public static final int MOD = 27;
  public static final int INT = 28;
  public static final int INTEGER = 29;
  public static final int LAND = 30;
  public static final int LB = 31;
  public static final int RB = 32;
  public static final int LCBR = 33;
  public static final int RCBR = 34;
  public static final int RETURN = 35;
  public static final int SEMI = 36;
  public static final int STATIC = 37;
  public static final int STRING = 38;
  public static final int QUOTE = 39;
  public static final int THIS = 40;
  public static final int VOID = 41;
  public static final int LENGTH = 42;
  public static final int WHILE = 43;
  public static final int FOR = 44;
  public static final int LNEG = 45;
  public static final int LOR = 46;
  public static final int NEW = 47;
  public static final int NULL = 48;
  public static final int EOF = 49;
  
}
