/* The following code was generated by JFlex 1.4.3 on 11/13/12 3:43 PM */

package IC.Parser;
import java_cup.runtime.Symbol;
import IC.Parser.LexicalError;


/**
 * This class is a scanner generated by 
 * <a href="http://www.jflex.de/">JFlex</a> 1.4.3
 * on 11/13/12 3:43 PM from the specification file
 * <tt>IC.lex</tt>
 */
public class Lexer {

  /** This character denotes the end of file */
  public static final int YYEOF = -1;

  /** initial size of the lookahead buffer */
  private static final int ZZ_BUFFERSIZE = 16384;

  /** lexical states */
  public static final int STATE_STRING = 2;
  public static final int STATE_COMMENT2 = 6;
  public static final int YYINITIAL = 0;
  public static final int STATE_COMMENT1 = 4;

  /**
   * ZZ_LEXSTATE[l] is the state in the DFA for the lexical state l
   * ZZ_LEXSTATE[l+1] is the state in the DFA for the lexical state l
   *                  at the beginning of a line
   * l is of the form l = 2*k, k a non negative integer
   */
  private static final int ZZ_LEXSTATE[] = { 
     0,  0,  1,  1,  2,  2,  3, 3
  };

  /** 
   * Translates characters to character classes
   */
  private static final char [] ZZ_CMAP = {
     0,  0,  0,  0,  0,  0,  0,  0,  0, 50,  1,  0,  0,  0,  0,  0, 
     0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0, 
     2, 46, 48,  0,  0, 42, 45,  0,  7,  8, 41, 39, 35, 40, 36, 10, 
    12, 11, 11, 11, 11, 11, 11, 11, 11, 11,  0, 37, 44, 38, 43,  0, 
     0, 13, 13, 13, 13, 13, 13, 13, 13, 13, 13, 13, 13, 13, 13, 13, 
    13, 13, 13, 13, 13, 13, 13, 13, 13, 13, 13,  5, 49,  6,  0,  9, 
     0, 17, 33, 15, 26, 20, 28, 29, 30, 27, 14, 34, 16, 14, 23, 32, 
    14, 14, 19, 18, 21, 22, 31, 24, 25, 14, 14,  3, 47,  4,  0,  0
  };

  /** 
   * Translates DFA states to action switch labels.
   */
  private static final int [] ZZ_ACTION = zzUnpackAction();

  private static final String ZZ_ACTION_PACKED_0 =
    "\4\0\1\1\1\2\1\3\1\4\1\5\1\6\1\7"+
    "\1\10\1\11\2\12\1\13\15\14\1\15\1\16\1\17"+
    "\1\20\1\21\1\22\1\23\1\24\1\25\1\26\1\1"+
    "\1\27\1\1\1\30\1\31\1\32\1\33\1\1\1\34"+
    "\1\35\1\36\1\2\1\37\1\40\15\14\1\41\4\14"+
    "\1\42\1\43\1\44\1\45\1\46\1\47\1\50\1\51"+
    "\1\52\1\53\12\14\1\54\2\14\1\55\12\14\1\56"+
    "\1\14\1\57\1\60\1\61\2\14\1\62\2\14\1\63"+
    "\6\14\1\64\1\65\1\66\2\14\1\67\1\70\1\71"+
    "\1\72\3\14\1\73\1\74\1\75";

  private static int [] zzUnpackAction() {
    int [] result = new int[137];
    int offset = 0;
    offset = zzUnpackAction(ZZ_ACTION_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackAction(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }


  /** 
   * Translates a state to a row index in the transition table
   */
  private static final int [] ZZ_ROWMAP = zzUnpackRowMap();

  private static final String ZZ_ROWMAP_PACKED_0 =
    "\0\0\0\63\0\146\0\231\0\314\0\314\0\314\0\314"+
    "\0\314\0\314\0\314\0\314\0\377\0\u0132\0\u0165\0\u0198"+
    "\0\u01cb\0\u01fe\0\u0231\0\u0264\0\u0297\0\u02ca\0\u02fd\0\u0330"+
    "\0\u0363\0\u0396\0\u03c9\0\u03fc\0\u042f\0\314\0\314\0\314"+
    "\0\u0462\0\314\0\314\0\314\0\314\0\u0495\0\u04c8\0\u04fb"+
    "\0\u052e\0\u0561\0\314\0\u0594\0\314\0\314\0\u05c7\0\314"+
    "\0\314\0\314\0\u05fa\0\314\0\314\0\u062d\0\u0660\0\u0693"+
    "\0\u06c6\0\u06f9\0\u072c\0\u075f\0\u0792\0\u07c5\0\u07f8\0\u082b"+
    "\0\u085e\0\u0891\0\u01cb\0\u08c4\0\u08f7\0\u092a\0\u095d\0\314"+
    "\0\314\0\314\0\314\0\314\0\314\0\314\0\314\0\314"+
    "\0\314\0\u0990\0\u09c3\0\u09f6\0\u0a29\0\u0a5c\0\u0a8f\0\u0ac2"+
    "\0\u0af5\0\u0b28\0\u0b5b\0\u01cb\0\u0b8e\0\u0bc1\0\u01cb\0\u0bf4"+
    "\0\u0c27\0\u0c5a\0\u0c8d\0\u0cc0\0\u0cf3\0\u0d26\0\u0d59\0\u0d8c"+
    "\0\u0dbf\0\u01cb\0\u0df2\0\u01cb\0\u01cb\0\u01cb\0\u0e25\0\u0e58"+
    "\0\u01cb\0\u0e8b\0\u0ebe\0\u01cb\0\u0ef1\0\u0f24\0\u0f57\0\u0f8a"+
    "\0\u0fbd\0\u0ff0\0\u01cb\0\u01cb\0\u01cb\0\u1023\0\u1056\0\u01cb"+
    "\0\u01cb\0\u01cb\0\u01cb\0\u1089\0\u10bc\0\u10ef\0\u01cb\0\u01cb"+
    "\0\u01cb";

  private static int [] zzUnpackRowMap() {
    int [] result = new int[137];
    int offset = 0;
    offset = zzUnpackRowMap(ZZ_ROWMAP_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackRowMap(String packed, int offset, int [] result) {
    int i = 0;  /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int high = packed.charAt(i++) << 16;
      result[j++] = high | packed.charAt(i++);
    }
    return j;
  }

  /** 
   * The transition table of the DFA
   */
  private static final int [] ZZ_TRANS = zzUnpackTrans();

  private static final String ZZ_TRANS_PACKED_0 =
    "\1\5\2\6\1\7\1\10\1\11\1\12\1\13\1\14"+
    "\1\5\1\15\1\16\1\17\1\20\1\21\1\22\1\23"+
    "\1\21\1\24\1\25\1\26\1\27\1\21\1\30\1\31"+
    "\2\21\1\32\1\33\2\21\1\34\1\21\1\35\1\21"+
    "\1\36\1\37\1\40\1\41\1\42\1\43\1\44\1\45"+
    "\1\46\1\47\1\50\1\51\1\52\1\53\1\5\1\6"+
    "\1\54\1\55\56\54\1\56\1\57\1\5\51\6\1\60"+
    "\11\6\12\61\1\62\36\61\1\6\11\61\75\0\1\63"+
    "\36\0\1\64\24\0\2\16\61\0\1\65\1\17\57\0"+
    "\1\20\1\0\30\20\31\0\1\21\1\0\30\21\31\0"+
    "\1\21\1\0\5\21\1\66\17\21\1\67\2\21\31\0"+
    "\1\21\1\0\11\21\1\70\16\21\31\0\1\21\1\0"+
    "\12\21\1\71\15\21\31\0\1\21\1\0\11\21\1\72"+
    "\16\21\31\0\1\21\1\0\5\21\1\73\10\21\1\74"+
    "\11\21\31\0\1\21\1\0\10\21\1\75\12\21\1\76"+
    "\4\21\31\0\1\21\1\0\11\21\1\77\1\21\1\100"+
    "\14\21\31\0\1\21\1\0\23\21\1\101\4\21\31\0"+
    "\1\21\1\0\14\21\1\102\4\21\1\103\6\21\31\0"+
    "\1\21\1\0\6\21\1\104\21\21\31\0\1\21\1\0"+
    "\25\21\1\105\2\21\31\0\1\21\1\0\10\21\1\106"+
    "\14\21\1\107\2\21\66\0\1\110\62\0\1\111\62\0"+
    "\1\112\71\0\1\113\53\0\1\114\73\0\1\115\3\0"+
    "\1\54\1\0\56\54\30\0\1\116\1\0\1\117\30\0"+
    "\1\120\1\121\1\0\1\63\1\0\61\63\11\0\1\21"+
    "\1\0\6\21\1\122\21\21\31\0\1\21\1\0\14\21"+
    "\1\123\13\21\31\0\1\21\1\0\14\21\1\124\13\21"+
    "\31\0\1\21\1\0\6\21\1\125\1\21\1\126\17\21"+
    "\31\0\1\21\1\0\12\21\1\127\15\21\31\0\1\21"+
    "\1\0\7\21\1\130\20\21\31\0\1\21\1\0\12\21"+
    "\1\131\15\21\31\0\1\21\1\0\13\21\1\132\14\21"+
    "\31\0\1\21\1\0\20\21\1\133\7\21\31\0\1\21"+
    "\1\0\15\21\1\134\12\21\31\0\1\21\1\0\5\21"+
    "\1\135\22\21\31\0\1\21\1\0\20\21\1\136\7\21"+
    "\31\0\1\21\1\0\12\21\1\137\15\21\31\0\1\21"+
    "\1\0\5\21\1\140\22\21\31\0\1\21\1\0\20\21"+
    "\1\141\7\21\31\0\1\21\1\0\11\21\1\142\16\21"+
    "\31\0\1\21\1\0\25\21\1\143\2\21\31\0\1\21"+
    "\1\0\7\21\1\144\20\21\31\0\1\21\1\0\12\21"+
    "\1\145\15\21\31\0\1\21\1\0\22\21\1\146\5\21"+
    "\31\0\1\21\1\0\12\21\1\147\15\21\31\0\1\21"+
    "\1\0\20\21\1\150\7\21\31\0\1\21\1\0\13\21"+
    "\1\151\14\21\31\0\1\21\1\0\11\21\1\152\16\21"+
    "\31\0\1\21\1\0\11\21\1\153\16\21\31\0\1\21"+
    "\1\0\11\21\1\154\16\21\31\0\1\21\1\0\7\21"+
    "\1\155\20\21\31\0\1\21\1\0\5\21\1\156\22\21"+
    "\31\0\1\21\1\0\5\21\1\157\22\21\31\0\1\21"+
    "\1\0\7\21\1\160\20\21\31\0\1\21\1\0\17\21"+
    "\1\161\10\21\31\0\1\21\1\0\6\21\1\162\21\21"+
    "\31\0\1\21\1\0\5\21\1\163\22\21\31\0\1\21"+
    "\1\0\7\21\1\164\20\21\31\0\1\21\1\0\20\21"+
    "\1\165\7\21\31\0\1\21\1\0\12\21\1\166\15\21"+
    "\31\0\1\21\1\0\20\21\1\167\7\21\31\0\1\21"+
    "\1\0\14\21\1\170\13\21\31\0\1\21\1\0\10\21"+
    "\1\171\17\21\31\0\1\21\1\0\14\21\1\172\13\21"+
    "\31\0\1\21\1\0\11\21\1\173\16\21\31\0\1\21"+
    "\1\0\11\21\1\174\16\21\31\0\1\21\1\0\27\21"+
    "\1\175\31\0\1\21\1\0\11\21\1\176\16\21\31\0"+
    "\1\21\1\0\14\21\1\177\13\21\31\0\1\21\1\0"+
    "\23\21\1\200\4\21\31\0\1\21\1\0\4\21\1\201"+
    "\23\21\31\0\1\21\1\0\22\21\1\202\5\21\31\0"+
    "\1\21\1\0\14\21\1\203\13\21\31\0\1\21\1\0"+
    "\17\21\1\204\10\21\31\0\1\21\1\0\6\21\1\205"+
    "\21\21\31\0\1\21\1\0\13\21\1\206\14\21\31\0"+
    "\1\21\1\0\7\21\1\207\20\21\31\0\1\21\1\0"+
    "\14\21\1\210\13\21\31\0\1\21\1\0\11\21\1\211"+
    "\16\21\20\0";

  private static int [] zzUnpackTrans() {
    int [] result = new int[4386];
    int offset = 0;
    offset = zzUnpackTrans(ZZ_TRANS_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackTrans(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      value--;
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }


  /* error codes */
  private static final int ZZ_UNKNOWN_ERROR = 0;
  private static final int ZZ_NO_MATCH = 1;
  private static final int ZZ_PUSHBACK_2BIG = 2;

  /* error messages for the codes above */
  private static final String ZZ_ERROR_MSG[] = {
    "Unkown internal scanner error",
    "Error: could not match input",
    "Error: pushback value was too large"
  };

  /**
   * ZZ_ATTRIBUTE[aState] contains the attributes of state <code>aState</code>
   */
  private static final int [] ZZ_ATTRIBUTE = zzUnpackAttribute();

  private static final String ZZ_ATTRIBUTE_PACKED_0 =
    "\4\0\10\11\21\1\3\11\1\1\4\11\5\1\1\11"+
    "\1\1\2\11\1\1\3\11\1\1\2\11\22\1\12\11"+
    "\70\1";

  private static int [] zzUnpackAttribute() {
    int [] result = new int[137];
    int offset = 0;
    offset = zzUnpackAttribute(ZZ_ATTRIBUTE_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackAttribute(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }

  /** the input device */
  private java.io.Reader zzReader;

  /** the current state of the DFA */
  private int zzState;

  /** the current lexical state */
  private int zzLexicalState = YYINITIAL;

  /** this buffer contains the current text to be matched and is
      the source of the yytext() string */
  private char zzBuffer[] = new char[ZZ_BUFFERSIZE];

  /** the textposition at the last accepting state */
  private int zzMarkedPos;

  /** the current text position in the buffer */
  private int zzCurrentPos;

  /** startRead marks the beginning of the yytext() string in the buffer */
  private int zzStartRead;

  /** endRead marks the last character in the buffer, that has been read
      from input */
  private int zzEndRead;

  /** number of newlines encountered up to the start of the matched text */
  private int yyline;

  /** the number of characters up to the start of the matched text */
  private int yychar;

  /**
   * the number of characters from the last newline up to the start of the 
   * matched text
   */
  private int yycolumn;

  /** 
   * zzAtBOL == true <=> the scanner is currently at the beginning of a line
   */
  private boolean zzAtBOL = true;

  /** zzAtEOF == true <=> the scanner is at the EOF */
  private boolean zzAtEOF;

  /** denotes if the user-EOF-code has already been executed */
  private boolean zzEOFDone;

  /* user code: */
	StringBuffer string = new StringBuffer();
	
	private Token token(int type){
		return new Token(type,yyline+1,yycolumn);
	}

	private Token token(int type, Object value){
		return new Token(type,yyline+1,yycolumn,value);
	}


  /**
   * Creates a new scanner
   * There is also a java.io.InputStream version of this constructor.
   *
   * @param   in  the java.io.Reader to read input from.
   */
  public Lexer(java.io.Reader in) {
    this.zzReader = in;
  }

  /**
   * Creates a new scanner.
   * There is also java.io.Reader version of this constructor.
   *
   * @param   in  the java.io.Inputstream to read input from.
   */
  public Lexer(java.io.InputStream in) {
    this(new java.io.InputStreamReader(in));
  }


  /**
   * Refills the input buffer.
   *
   * @return      <code>false</code>, iff there was new input.
   * 
   * @exception   java.io.IOException  if any I/O-Error occurs
   */
  private boolean zzRefill() throws java.io.IOException {

    /* first: make room (if you can) */
    if (zzStartRead > 0) {
      System.arraycopy(zzBuffer, zzStartRead,
                       zzBuffer, 0,
                       zzEndRead-zzStartRead);

      /* translate stored positions */
      zzEndRead-= zzStartRead;
      zzCurrentPos-= zzStartRead;
      zzMarkedPos-= zzStartRead;
      zzStartRead = 0;
    }

    /* is the buffer big enough? */
    if (zzCurrentPos >= zzBuffer.length) {
      /* if not: blow it up */
      char newBuffer[] = new char[zzCurrentPos*2];
      System.arraycopy(zzBuffer, 0, newBuffer, 0, zzBuffer.length);
      zzBuffer = newBuffer;
    }

    /* finally: fill the buffer with new input */
    int numRead = zzReader.read(zzBuffer, zzEndRead,
                                            zzBuffer.length-zzEndRead);

    if (numRead > 0) {
      zzEndRead+= numRead;
      return false;
    }
    // unlikely but not impossible: read 0 characters, but not at end of stream    
    if (numRead == 0) {
      int c = zzReader.read();
      if (c == -1) {
        return true;
      } else {
        zzBuffer[zzEndRead++] = (char) c;
        return false;
      }     
    }

	// numRead < 0
    return true;
  }

    
  /**
   * Closes the input stream.
   */
  public final void yyclose() throws java.io.IOException {
    zzAtEOF = true;            /* indicate end of file */
    zzEndRead = zzStartRead;  /* invalidate buffer    */

    if (zzReader != null)
      zzReader.close();
  }


  /**
   * Resets the scanner to read from a new input stream.
   * Does not close the old reader.
   *
   * All internal variables are reset, the old input stream 
   * <b>cannot</b> be reused (internal buffer is discarded and lost).
   * Lexical state is set to <tt>ZZ_INITIAL</tt>.
   *
   * @param reader   the new input stream 
   */
  public final void yyreset(java.io.Reader reader) {
    zzReader = reader;
    zzAtBOL  = true;
    zzAtEOF  = false;
    zzEOFDone = false;
    zzEndRead = zzStartRead = 0;
    zzCurrentPos = zzMarkedPos = 0;
    yyline = yychar = yycolumn = 0;
    zzLexicalState = YYINITIAL;
  }


  /**
   * Returns the current lexical state.
   */
  public final int yystate() {
    return zzLexicalState;
  }


  /**
   * Enters a new lexical state
   *
   * @param newState the new lexical state
   */
  public final void yybegin(int newState) {
    zzLexicalState = newState;
  }


  /**
   * Returns the text matched by the current regular expression.
   */
  public final String yytext() {
    return new String( zzBuffer, zzStartRead, zzMarkedPos-zzStartRead );
  }


  /**
   * Returns the character at position <tt>pos</tt> from the 
   * matched text. 
   * 
   * It is equivalent to yytext().charAt(pos), but faster
   *
   * @param pos the position of the character to fetch. 
   *            A value from 0 to yylength()-1.
   *
   * @return the character at position pos
   */
  public final char yycharat(int pos) {
    return zzBuffer[zzStartRead+pos];
  }


  /**
   * Returns the length of the matched text region.
   */
  public final int yylength() {
    return zzMarkedPos-zzStartRead;
  }


  /**
   * Reports an error that occured while scanning.
   *
   * In a wellformed scanner (no or only correct usage of 
   * yypushback(int) and a match-all fallback rule) this method 
   * will only be called with things that "Can't Possibly Happen".
   * If this method is called, something is seriously wrong
   * (e.g. a JFlex bug producing a faulty scanner etc.).
   *
   * Usual syntax/scanner level error handling should be done
   * in error fallback rules.
   *
   * @param   errorCode  the code of the errormessage to display
   */
  private void zzScanError(int errorCode) throws LexicalError {
    String message;
    try {
      message = ZZ_ERROR_MSG[errorCode];
    }
    catch (ArrayIndexOutOfBoundsException e) {
      message = ZZ_ERROR_MSG[ZZ_UNKNOWN_ERROR];
    }

    throw new LexicalError(message);
  } 


  /**
   * Pushes the specified amount of characters back into the input stream.
   *
   * They will be read again by then next call of the scanning method
   *
   * @param number  the number of characters to be read again.
   *                This number must not be greater than yylength()!
   */
  public void yypushback(int number)  throws LexicalError {
    if ( number > yylength() )
      zzScanError(ZZ_PUSHBACK_2BIG);

    zzMarkedPos -= number;
  }


  /**
   * Resumes scanning until the next regular expression is matched,
   * the end of input is encountered or an I/O-Error occurs.
   *
   * @return      the next token
   * @exception   java.io.IOException  if any I/O-Error occurs
   */
  public Token next_token() throws java.io.IOException, LexicalError {
    int zzInput;
    int zzAction;

    // cached fields:
    int zzCurrentPosL;
    int zzMarkedPosL;
    int zzEndReadL = zzEndRead;
    char [] zzBufferL = zzBuffer;
    char [] zzCMapL = ZZ_CMAP;

    int [] zzTransL = ZZ_TRANS;
    int [] zzRowMapL = ZZ_ROWMAP;
    int [] zzAttrL = ZZ_ATTRIBUTE;

    while (true) {
      zzMarkedPosL = zzMarkedPos;

      boolean zzR = false;
      for (zzCurrentPosL = zzStartRead; zzCurrentPosL < zzMarkedPosL;
                                                             zzCurrentPosL++) {
        switch (zzBufferL[zzCurrentPosL]) {
        case '\u000B':
        case '\u000C':
        case '\u0085':
        case '\u2028':
        case '\u2029':
          yyline++;
          yycolumn = 0;
          zzR = false;
          break;
        case '\r':
          yyline++;
          yycolumn = 0;
          zzR = true;
          break;
        case '\n':
          if (zzR)
            zzR = false;
          else {
            yyline++;
            yycolumn = 0;
          }
          break;
        default:
          zzR = false;
          yycolumn++;
        }
      }

      if (zzR) {
        // peek one character ahead if it is \n (if we have counted one line too much)
        boolean zzPeek;
        if (zzMarkedPosL < zzEndReadL)
          zzPeek = zzBufferL[zzMarkedPosL] == '\n';
        else if (zzAtEOF)
          zzPeek = false;
        else {
          boolean eof = zzRefill();
          zzEndReadL = zzEndRead;
          zzMarkedPosL = zzMarkedPos;
          zzBufferL = zzBuffer;
          if (eof) 
            zzPeek = false;
          else 
            zzPeek = zzBufferL[zzMarkedPosL] == '\n';
        }
        if (zzPeek) yyline--;
      }
      zzAction = -1;

      zzCurrentPosL = zzCurrentPos = zzStartRead = zzMarkedPosL;
  
      zzState = ZZ_LEXSTATE[zzLexicalState];


      zzForAction: {
        while (true) {
    
          if (zzCurrentPosL < zzEndReadL)
            zzInput = zzBufferL[zzCurrentPosL++];
          else if (zzAtEOF) {
            zzInput = YYEOF;
            break zzForAction;
          }
          else {
            // store back cached positions
            zzCurrentPos  = zzCurrentPosL;
            zzMarkedPos   = zzMarkedPosL;
            boolean eof = zzRefill();
            // get translated positions and possibly new buffer
            zzCurrentPosL  = zzCurrentPos;
            zzMarkedPosL   = zzMarkedPos;
            zzBufferL      = zzBuffer;
            zzEndReadL     = zzEndRead;
            if (eof) {
              zzInput = YYEOF;
              break zzForAction;
            }
            else {
              zzInput = zzBufferL[zzCurrentPosL++];
            }
          }
          int zzNext = zzTransL[ zzRowMapL[zzState] + zzCMapL[zzInput] ];
          if (zzNext == -1) break zzForAction;
          zzState = zzNext;

          int zzAttributes = zzAttrL[zzState];
          if ( (zzAttributes & 1) == 1 ) {
            zzAction = zzState;
            zzMarkedPosL = zzCurrentPosL;
            if ( (zzAttributes & 8) == 8 ) break zzForAction;
          }

        }
      }

      // store back cached position
      zzMarkedPos = zzMarkedPosL;

      switch (zzAction < 0 ? zzAction : ZZ_ACTION[zzAction]) {
        case 2: 
          { /* ignore */
          }
        case 62: break;
        case 44: 
          { return token(sym.NEW);
          }
        case 63: break;
        case 37: 
          { return token(sym.LAND);
          }
        case 64: break;
        case 4: 
          { return token(sym.RCBR);
          }
        case 65: break;
        case 18: 
          { return token(sym.MINUS);
          }
        case 66: break;
        case 1: 
          { throw new LexicalError("illegal character '"+yytext()+"'", yyline+1);
          }
        case 67: break;
        case 35: 
          { return token(sym.GTE);
          }
        case 68: break;
        case 55: 
          { return token(sym.LENGTH);
          }
        case 69: break;
        case 14: 
          { return token(sym.DOT);
          }
        case 70: break;
        case 13: 
          { return token(sym.COMMA);
          }
        case 71: break;
        case 17: 
          { return token(sym.PLUS);
          }
        case 72: break;
        case 8: 
          { return token(sym.RP);
          }
        case 73: break;
        case 59: 
          { return token(sym.EXTENDS);
          }
        case 74: break;
        case 39: 
          { return token(sym.LOR);
          }
        case 75: break;
        case 53: 
          { return token(sym.FALSE);
          }
        case 76: break;
        case 47: 
          { return token(sym.TRUE);
          }
        case 77: break;
        case 21: 
          { return token(sym.GT);
          }
        case 78: break;
        case 43: 
          { string.append('\\');
          }
        case 79: break;
        case 50: 
          { return token(sym.VOID);
          }
        case 80: break;
        case 22: 
          { return token(sym.LT);
          }
        case 81: break;
        case 51: 
          { return token(sym.CLASS);
          }
        case 82: break;
        case 40: 
          { string.append("\\t");
          }
        case 83: break;
        case 46: 
          { return token(sym.ELSE);
          }
        case 84: break;
        case 30: 
          { yybegin(YYINITIAL);
          }
        case 85: break;
        case 16: 
          { return token(sym.ASSIGN);
          }
        case 86: break;
        case 5: 
          { return token(sym.LB);
          }
        case 87: break;
        case 58: 
          { return token(sym.RETURN);
          }
        case 88: break;
        case 10: 
          { int a;
	 try { a = Integer.parseInt(yytext()); }
	 catch (Exception e) { throw new LexicalError("Number is too long.", yyline+1); }
		return token(sym.INTEGER, a);
          }
        case 89: break;
        case 45: 
          { return token(sym.INT);
          }
        case 90: break;
        case 23: 
          { return token(sym.LNEG);
          }
        case 91: break;
        case 48: 
          { return token(sym.THIS);
          }
        case 92: break;
        case 42: 
          { string.append('\"');
          }
        case 93: break;
        case 12: 
          { return token(sym.ID, yytext());
          }
        case 94: break;
        case 15: 
          { return token(sym.SEMI);
          }
        case 95: break;
        case 56: 
          { return token(sym.STATIC);
          }
        case 96: break;
        case 20: 
          { return token(sym.MOD);
          }
        case 97: break;
        case 26: 
          { throw new LexicalError("Unterminated string at end of line.", yyline+1);
          }
        case 98: break;
        case 60: 
          { return token(sym.BOOLEAN);
          }
        case 99: break;
        case 33: 
          { return token(sym.IF);
          }
        case 100: break;
        case 32: 
          { throw new LexicalError("A number must not begin with zeros.", yyline+1);
          }
        case 101: break;
        case 28: 
          { yybegin(STATE_COMMENT2);
          }
        case 102: break;
        case 25: 
          { string.append(yytext());
          }
        case 103: break;
        case 24: 
          { string.setLength(0); string.append('"'); yybegin(STATE_STRING);
          }
        case 104: break;
        case 19: 
          { return token(sym.MULTIPLY);
          }
        case 105: break;
        case 7: 
          { return token(sym.LP);
          }
        case 106: break;
        case 36: 
          { return token(sym.LTE);
          }
        case 107: break;
        case 38: 
          { return token(sym.NEQUAL);
          }
        case 108: break;
        case 34: 
          { return token(sym.EQUAL);
          }
        case 109: break;
        case 54: 
          { return token(sym.BREAK);
          }
        case 110: break;
        case 49: 
          { return token(sym.NULL);
          }
        case 111: break;
        case 31: 
          { yybegin(STATE_COMMENT1);
          }
        case 112: break;
        case 61: 
          { return token(sym.CONTINUE);
          }
        case 113: break;
        case 52: 
          { return token(sym.WHILE);
          }
        case 114: break;
        case 6: 
          { return token(sym.RB);
          }
        case 115: break;
        case 29: 
          { yybegin(STATE_COMMENT1) ;
          }
        case 116: break;
        case 41: 
          { string.append("\\n");
          }
        case 117: break;
        case 11: 
          { return token(sym.CLASS_ID, yytext());
          }
        case 118: break;
        case 27: 
          { string.append('"'); yybegin(YYINITIAL); return token(sym.QUOTE,string.toString());
          }
        case 119: break;
        case 3: 
          { return token(sym.LCBR);
          }
        case 120: break;
        case 57: 
          { return token(sym.STRING);
          }
        case 121: break;
        case 9: 
          { return token(sym.DIVIDE);
          }
        case 122: break;
        default: 
          if (zzInput == YYEOF && zzStartRead == zzCurrentPos) {
            zzAtEOF = true;
              { 	
	/* EOF inside a string */
	if(yystate() == STATE_STRING)   
		throw new LexicalError("Unterminated string at end of file.",yyline+1);
	
	/* EOF inside comment */	
	if(yystate() == STATE_COMMENT1 || yystate() == STATE_COMMENT2)   
		throw new LexicalError("Unclosed comment at end of file.",yyline+1);
		 
	return new Token(sym.EOF,yyline+1,yycolumn);

 }
          } 
          else {
            zzScanError(ZZ_NO_MATCH);
          }
      }
    }
  }


}
