/* The following code was generated by JFlex 1.4.3 on 11/7/12 10:27 AM */

package IC.Parser;
import java_cup.runtime.Symbol;


/**
 * This class is a scanner generated by 
 * <a href="http://www.jflex.de/">JFlex</a> 1.4.3
 * on 11/7/12 10:27 AM from the specification file
 * <tt>IC.lex</tt>
 */
public class Lexer {

  /** This character denotes the end of file */
  public static final int YYEOF = -1;

  /** initial size of the lookahead buffer */
  private static final int ZZ_BUFFERSIZE = 16384;

  /** lexical states */
  public static final int STATE_COMMENT = 4;
  public static final int STATE_INLINE_COMMENT = 6;
  public static final int STATE_STRING = 2;
  public static final int YYINITIAL = 0;

  /**
   * ZZ_LEXSTATE[l] is the state in the DFA for the lexical state l
   * ZZ_LEXSTATE[l+1] is the state in the DFA for the lexical state l
   *                  at the beginning of a line
   * l is of the form l = 2*k, k a non negative integer
   */
  private static final int ZZ_LEXSTATE[] = { 
     0,  0,  1,  1,  2,  2,  3, 3
  };

  /** 
   * Translates characters to character classes
   */
  private static final char [] ZZ_CMAP = {
     0,  0,  0,  0,  0,  0,  0,  0,  0, 49,  1,  0,  3,  2,  0,  0, 
     0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0, 
     3, 45, 47,  0,  0, 41, 44,  0,  8,  9, 40, 39, 35, 13, 36, 11, 
    14, 12, 12, 12, 12, 12, 12, 12, 12, 12,  0, 37, 43, 38, 42,  0, 
     0, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 
    10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10,  6, 48,  7,  0, 10, 
     0, 17, 33, 15, 26, 20, 28, 29, 30, 27, 10, 34, 16, 10, 23, 32, 
    10, 10, 19, 18, 21, 22, 31, 24, 25, 10, 10,  4, 46,  5,  0,  0
  };

  /** 
   * Translates DFA states to action switch labels.
   */
  private static final int [] ZZ_ACTION = zzUnpackAction();

  private static final String ZZ_ACTION_PACKED_0 =
    "\4\0\1\1\1\2\1\3\1\4\1\5\1\6\1\7"+
    "\1\10\1\11\1\12\1\13\1\12\14\10\1\14\1\15"+
    "\1\16\1\17\1\20\1\21\1\22\1\23\1\24\1\0"+
    "\1\25\1\0\1\26\1\27\1\30\1\31\2\0\1\32"+
    "\1\0\1\33\15\10\1\34\4\10\1\35\1\36\1\37"+
    "\1\40\1\41\1\42\1\43\1\44\1\45\1\46\1\47"+
    "\12\10\1\50\2\10\1\51\12\10\1\52\1\10\1\53"+
    "\1\54\1\55\2\10\1\56\2\10\1\57\6\10\1\60"+
    "\1\61\1\62\2\10\1\63\1\64\1\65\1\66\3\10"+
    "\1\67\1\70\1\71";

  private static int [] zzUnpackAction() {
    int [] result = new int[134];
    int offset = 0;
    offset = zzUnpackAction(ZZ_ACTION_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackAction(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }


  /** 
   * Translates a state to a row index in the transition table
   */
  private static final int [] ZZ_ROWMAP = zzUnpackRowMap();

  private static final String ZZ_ROWMAP_PACKED_0 =
    "\0\0\0\62\0\144\0\226\0\310\0\310\0\310\0\310"+
    "\0\310\0\310\0\310\0\372\0\u012c\0\u015e\0\u0190\0\u01c2"+
    "\0\u01f4\0\u0226\0\u0258\0\u028a\0\u02bc\0\u02ee\0\u0320\0\u0352"+
    "\0\u0384\0\u03b6\0\u03e8\0\u041a\0\310\0\310\0\310\0\u044c"+
    "\0\310\0\310\0\310\0\u047e\0\u04b0\0\u04e2\0\u0514\0\u0546"+
    "\0\310\0\u0578\0\310\0\310\0\u05aa\0\u05dc\0\310\0\u060e"+
    "\0\310\0\u0640\0\u0672\0\u06a4\0\u06d6\0\u0708\0\u073a\0\u076c"+
    "\0\u079e\0\u07d0\0\u0802\0\u0834\0\u0866\0\u0898\0\372\0\u08ca"+
    "\0\u08fc\0\u092e\0\u0960\0\310\0\310\0\310\0\310\0\310"+
    "\0\310\0\310\0\310\0\310\0\310\0\310\0\u0992\0\u09c4"+
    "\0\u09f6\0\u0a28\0\u0a5a\0\u0a8c\0\u0abe\0\u0af0\0\u0b22\0\u0b54"+
    "\0\372\0\u0b86\0\u0bb8\0\372\0\u0bea\0\u0c1c\0\u0c4e\0\u0c80"+
    "\0\u0cb2\0\u0ce4\0\u0d16\0\u0d48\0\u0d7a\0\u0dac\0\372\0\u0dde"+
    "\0\372\0\372\0\372\0\u0e10\0\u0e42\0\372\0\u0e74\0\u0ea6"+
    "\0\372\0\u0ed8\0\u0f0a\0\u0f3c\0\u0f6e\0\u0fa0\0\u0fd2\0\372"+
    "\0\372\0\372\0\u1004\0\u1036\0\372\0\372\0\372\0\372"+
    "\0\u1068\0\u109a\0\u10cc\0\372\0\372\0\372";

  private static int [] zzUnpackRowMap() {
    int [] result = new int[134];
    int offset = 0;
    offset = zzUnpackRowMap(ZZ_ROWMAP_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackRowMap(String packed, int offset, int [] result) {
    int i = 0;  /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int high = packed.charAt(i++) << 16;
      result[j++] = high | packed.charAt(i++);
    }
    return j;
  }

  /** 
   * The transition table of the DFA
   */
  private static final int [] ZZ_TRANS = zzUnpackTrans();

  private static final String ZZ_TRANS_PACKED_0 =
    "\1\0\3\5\1\6\1\7\1\10\1\11\1\12\1\13"+
    "\1\14\1\15\1\16\1\17\1\20\1\21\1\22\1\14"+
    "\1\23\1\24\1\25\1\26\1\14\1\27\1\30\2\14"+
    "\1\31\1\32\2\14\1\33\1\14\1\34\1\14\1\35"+
    "\1\36\1\37\1\40\1\41\1\42\1\43\1\44\1\45"+
    "\1\46\1\47\1\50\1\51\1\0\1\5\1\52\1\53"+
    "\55\52\1\54\1\55\1\0\50\5\1\56\12\5\1\57"+
    "\60\5\74\0\1\14\1\0\1\14\1\0\25\14\32\0"+
    "\1\60\34\0\1\61\25\0\1\16\1\0\1\16\57\0"+
    "\1\16\1\0\1\20\61\0\1\20\55\0\1\14\1\0"+
    "\1\14\1\0\2\14\1\62\17\14\1\63\2\14\31\0"+
    "\1\14\1\0\1\14\1\0\6\14\1\64\16\14\31\0"+
    "\1\14\1\0\1\14\1\0\7\14\1\65\15\14\31\0"+
    "\1\14\1\0\1\14\1\0\6\14\1\66\16\14\31\0"+
    "\1\14\1\0\1\14\1\0\2\14\1\67\10\14\1\70"+
    "\11\14\31\0\1\14\1\0\1\14\1\0\5\14\1\71"+
    "\12\14\1\72\4\14\31\0\1\14\1\0\1\14\1\0"+
    "\6\14\1\73\1\14\1\74\14\14\31\0\1\14\1\0"+
    "\1\14\1\0\20\14\1\75\4\14\31\0\1\14\1\0"+
    "\1\14\1\0\11\14\1\76\4\14\1\77\6\14\31\0"+
    "\1\14\1\0\1\14\1\0\3\14\1\100\21\14\31\0"+
    "\1\14\1\0\1\14\1\0\22\14\1\101\2\14\31\0"+
    "\1\14\1\0\1\14\1\0\5\14\1\102\14\14\1\103"+
    "\2\14\65\0\1\104\61\0\1\105\61\0\1\106\67\0"+
    "\1\107\53\0\1\110\71\0\1\111\3\0\1\52\1\0"+
    "\55\52\30\0\1\112\1\0\1\113\27\0\1\114\1\115"+
    "\14\0\1\57\46\0\1\60\2\116\57\60\12\0\1\14"+
    "\1\0\1\14\1\0\3\14\1\117\21\14\31\0\1\14"+
    "\1\0\1\14\1\0\11\14\1\120\13\14\31\0\1\14"+
    "\1\0\1\14\1\0\11\14\1\121\13\14\31\0\1\14"+
    "\1\0\1\14\1\0\3\14\1\122\1\14\1\123\17\14"+
    "\31\0\1\14\1\0\1\14\1\0\7\14\1\124\15\14"+
    "\31\0\1\14\1\0\1\14\1\0\4\14\1\125\20\14"+
    "\31\0\1\14\1\0\1\14\1\0\7\14\1\126\15\14"+
    "\31\0\1\14\1\0\1\14\1\0\10\14\1\127\14\14"+
    "\31\0\1\14\1\0\1\14\1\0\15\14\1\130\7\14"+
    "\31\0\1\14\1\0\1\14\1\0\12\14\1\131\12\14"+
    "\31\0\1\14\1\0\1\14\1\0\2\14\1\132\22\14"+
    "\31\0\1\14\1\0\1\14\1\0\15\14\1\133\7\14"+
    "\31\0\1\14\1\0\1\14\1\0\7\14\1\134\15\14"+
    "\31\0\1\14\1\0\1\14\1\0\2\14\1\135\22\14"+
    "\31\0\1\14\1\0\1\14\1\0\15\14\1\136\7\14"+
    "\31\0\1\14\1\0\1\14\1\0\6\14\1\137\16\14"+
    "\31\0\1\14\1\0\1\14\1\0\22\14\1\140\2\14"+
    "\31\0\1\14\1\0\1\14\1\0\4\14\1\141\20\14"+
    "\31\0\1\14\1\0\1\14\1\0\7\14\1\142\15\14"+
    "\31\0\1\14\1\0\1\14\1\0\17\14\1\143\5\14"+
    "\31\0\1\14\1\0\1\14\1\0\7\14\1\144\15\14"+
    "\31\0\1\14\1\0\1\14\1\0\15\14\1\145\7\14"+
    "\31\0\1\14\1\0\1\14\1\0\10\14\1\146\14\14"+
    "\31\0\1\14\1\0\1\14\1\0\6\14\1\147\16\14"+
    "\31\0\1\14\1\0\1\14\1\0\6\14\1\150\16\14"+
    "\31\0\1\14\1\0\1\14\1\0\6\14\1\151\16\14"+
    "\31\0\1\14\1\0\1\14\1\0\4\14\1\152\20\14"+
    "\31\0\1\14\1\0\1\14\1\0\2\14\1\153\22\14"+
    "\31\0\1\14\1\0\1\14\1\0\2\14\1\154\22\14"+
    "\31\0\1\14\1\0\1\14\1\0\4\14\1\155\20\14"+
    "\31\0\1\14\1\0\1\14\1\0\14\14\1\156\10\14"+
    "\31\0\1\14\1\0\1\14\1\0\3\14\1\157\21\14"+
    "\31\0\1\14\1\0\1\14\1\0\2\14\1\160\22\14"+
    "\31\0\1\14\1\0\1\14\1\0\4\14\1\161\20\14"+
    "\31\0\1\14\1\0\1\14\1\0\15\14\1\162\7\14"+
    "\31\0\1\14\1\0\1\14\1\0\7\14\1\163\15\14"+
    "\31\0\1\14\1\0\1\14\1\0\15\14\1\164\7\14"+
    "\31\0\1\14\1\0\1\14\1\0\11\14\1\165\13\14"+
    "\31\0\1\14\1\0\1\14\1\0\5\14\1\166\17\14"+
    "\31\0\1\14\1\0\1\14\1\0\11\14\1\167\13\14"+
    "\31\0\1\14\1\0\1\14\1\0\6\14\1\170\16\14"+
    "\31\0\1\14\1\0\1\14\1\0\6\14\1\171\16\14"+
    "\31\0\1\14\1\0\1\14\1\0\24\14\1\172\31\0"+
    "\1\14\1\0\1\14\1\0\6\14\1\173\16\14\31\0"+
    "\1\14\1\0\1\14\1\0\11\14\1\174\13\14\31\0"+
    "\1\14\1\0\1\14\1\0\20\14\1\175\4\14\31\0"+
    "\1\14\1\0\1\14\1\0\1\14\1\176\23\14\31\0"+
    "\1\14\1\0\1\14\1\0\17\14\1\177\5\14\31\0"+
    "\1\14\1\0\1\14\1\0\11\14\1\200\13\14\31\0"+
    "\1\14\1\0\1\14\1\0\14\14\1\201\10\14\31\0"+
    "\1\14\1\0\1\14\1\0\3\14\1\202\21\14\31\0"+
    "\1\14\1\0\1\14\1\0\10\14\1\203\14\14\31\0"+
    "\1\14\1\0\1\14\1\0\4\14\1\204\20\14\31\0"+
    "\1\14\1\0\1\14\1\0\11\14\1\205\13\14\31\0"+
    "\1\14\1\0\1\14\1\0\6\14\1\206\16\14\17\0";

  private static int [] zzUnpackTrans() {
    int [] result = new int[4350];
    int offset = 0;
    offset = zzUnpackTrans(ZZ_TRANS_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackTrans(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      value--;
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }


  /* error codes */
  private static final int ZZ_UNKNOWN_ERROR = 0;
  private static final int ZZ_NO_MATCH = 1;
  private static final int ZZ_PUSHBACK_2BIG = 2;

  /* error messages for the codes above */
  private static final String ZZ_ERROR_MSG[] = {
    "Unkown internal scanner error",
    "Error: could not match input",
    "Error: pushback value was too large"
  };

  /**
   * ZZ_ATTRIBUTE[aState] contains the attributes of state <code>aState</code>
   */
  private static final int [] ZZ_ATTRIBUTE = zzUnpackAttribute();

  private static final String ZZ_ATTRIBUTE_PACKED_0 =
    "\4\0\7\11\21\1\3\11\1\1\3\11\2\1\1\0"+
    "\1\1\1\0\1\11\1\1\2\11\2\0\1\11\1\0"+
    "\1\11\22\1\13\11\70\1";

  private static int [] zzUnpackAttribute() {
    int [] result = new int[134];
    int offset = 0;
    offset = zzUnpackAttribute(ZZ_ATTRIBUTE_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackAttribute(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }

  /** the input device */
  private java.io.Reader zzReader;

  /** the current state of the DFA */
  private int zzState;

  /** the current lexical state */
  private int zzLexicalState = YYINITIAL;

  /** this buffer contains the current text to be matched and is
      the source of the yytext() string */
  private char zzBuffer[] = new char[ZZ_BUFFERSIZE];

  /** the textposition at the last accepting state */
  private int zzMarkedPos;

  /** the current text position in the buffer */
  private int zzCurrentPos;

  /** startRead marks the beginning of the yytext() string in the buffer */
  private int zzStartRead;

  /** endRead marks the last character in the buffer, that has been read
      from input */
  private int zzEndRead;

  /** number of newlines encountered up to the start of the matched text */
  private int yyline;

  /** the number of characters up to the start of the matched text */
  private int yychar;

  /**
   * the number of characters from the last newline up to the start of the 
   * matched text
   */
  private int yycolumn;

  /** 
   * zzAtBOL == true <=> the scanner is currently at the beginning of a line
   */
  private boolean zzAtBOL = true;

  /** zzAtEOF == true <=> the scanner is at the EOF */
  private boolean zzAtEOF;

  /** denotes if the user-EOF-code has already been executed */
  private boolean zzEOFDone;

  /* user code: */
	StringBuffer string = new StringBuffer();
	
	private Token token(int type){
		return new Token(type,yyline,yycolumn);
	}

	private Token token(int type, Object value){
		return new Token(type,yyline,yycolumn,value);
	}


  /**
   * Creates a new scanner
   * There is also a java.io.InputStream version of this constructor.
   *
   * @param   in  the java.io.Reader to read input from.
   */
  public Lexer(java.io.Reader in) {
    this.zzReader = in;
  }

  /**
   * Creates a new scanner.
   * There is also java.io.Reader version of this constructor.
   *
   * @param   in  the java.io.Inputstream to read input from.
   */
  public Lexer(java.io.InputStream in) {
    this(new java.io.InputStreamReader(in));
  }


  /**
   * Refills the input buffer.
   *
   * @return      <code>false</code>, iff there was new input.
   * 
   * @exception   java.io.IOException  if any I/O-Error occurs
   */
  private boolean zzRefill() throws java.io.IOException {

    /* first: make room (if you can) */
    if (zzStartRead > 0) {
      System.arraycopy(zzBuffer, zzStartRead,
                       zzBuffer, 0,
                       zzEndRead-zzStartRead);

      /* translate stored positions */
      zzEndRead-= zzStartRead;
      zzCurrentPos-= zzStartRead;
      zzMarkedPos-= zzStartRead;
      zzStartRead = 0;
    }

    /* is the buffer big enough? */
    if (zzCurrentPos >= zzBuffer.length) {
      /* if not: blow it up */
      char newBuffer[] = new char[zzCurrentPos*2];
      System.arraycopy(zzBuffer, 0, newBuffer, 0, zzBuffer.length);
      zzBuffer = newBuffer;
    }

    /* finally: fill the buffer with new input */
    int numRead = zzReader.read(zzBuffer, zzEndRead,
                                            zzBuffer.length-zzEndRead);

    if (numRead > 0) {
      zzEndRead+= numRead;
      return false;
    }
    // unlikely but not impossible: read 0 characters, but not at end of stream    
    if (numRead == 0) {
      int c = zzReader.read();
      if (c == -1) {
        return true;
      } else {
        zzBuffer[zzEndRead++] = (char) c;
        return false;
      }     
    }

	// numRead < 0
    return true;
  }

    
  /**
   * Closes the input stream.
   */
  public final void yyclose() throws java.io.IOException {
    zzAtEOF = true;            /* indicate end of file */
    zzEndRead = zzStartRead;  /* invalidate buffer    */

    if (zzReader != null)
      zzReader.close();
  }


  /**
   * Resets the scanner to read from a new input stream.
   * Does not close the old reader.
   *
   * All internal variables are reset, the old input stream 
   * <b>cannot</b> be reused (internal buffer is discarded and lost).
   * Lexical state is set to <tt>ZZ_INITIAL</tt>.
   *
   * @param reader   the new input stream 
   */
  public final void yyreset(java.io.Reader reader) {
    zzReader = reader;
    zzAtBOL  = true;
    zzAtEOF  = false;
    zzEOFDone = false;
    zzEndRead = zzStartRead = 0;
    zzCurrentPos = zzMarkedPos = 0;
    yyline = yychar = yycolumn = 0;
    zzLexicalState = YYINITIAL;
  }


  /**
   * Returns the current lexical state.
   */
  public final int yystate() {
    return zzLexicalState;
  }


  /**
   * Enters a new lexical state
   *
   * @param newState the new lexical state
   */
  public final void yybegin(int newState) {
    zzLexicalState = newState;
  }


  /**
   * Returns the text matched by the current regular expression.
   */
  public final String yytext() {
    return new String( zzBuffer, zzStartRead, zzMarkedPos-zzStartRead );
  }


  /**
   * Returns the character at position <tt>pos</tt> from the 
   * matched text. 
   * 
   * It is equivalent to yytext().charAt(pos), but faster
   *
   * @param pos the position of the character to fetch. 
   *            A value from 0 to yylength()-1.
   *
   * @return the character at position pos
   */
  public final char yycharat(int pos) {
    return zzBuffer[zzStartRead+pos];
  }


  /**
   * Returns the length of the matched text region.
   */
  public final int yylength() {
    return zzMarkedPos-zzStartRead;
  }


  /**
   * Reports an error that occured while scanning.
   *
   * In a wellformed scanner (no or only correct usage of 
   * yypushback(int) and a match-all fallback rule) this method 
   * will only be called with things that "Can't Possibly Happen".
   * If this method is called, something is seriously wrong
   * (e.g. a JFlex bug producing a faulty scanner etc.).
   *
   * Usual syntax/scanner level error handling should be done
   * in error fallback rules.
   *
   * @param   errorCode  the code of the errormessage to display
   */
  private void zzScanError(int errorCode) throws LexicalError {
    String message;
    try {
      message = ZZ_ERROR_MSG[errorCode];
    }
    catch (ArrayIndexOutOfBoundsException e) {
      message = ZZ_ERROR_MSG[ZZ_UNKNOWN_ERROR];
    }

    throw new LexicalError(message);
  } 


  /**
   * Pushes the specified amount of characters back into the input stream.
   *
   * They will be read again by then next call of the scanning method
   *
   * @param number  the number of characters to be read again.
   *                This number must not be greater than yylength()!
   */
  public void yypushback(int number)  throws LexicalError {
    if ( number > yylength() )
      zzScanError(ZZ_PUSHBACK_2BIG);

    zzMarkedPos -= number;
  }


  /**
   * Resumes scanning until the next regular expression is matched,
   * the end of input is encountered or an I/O-Error occurs.
   *
   * @return      the next token
   * @exception   java.io.IOException  if any I/O-Error occurs
   */
  public Token next_token() throws java.io.IOException, LexicalError {
    int zzInput;
    int zzAction;

    // cached fields:
    int zzCurrentPosL;
    int zzMarkedPosL;
    int zzEndReadL = zzEndRead;
    char [] zzBufferL = zzBuffer;
    char [] zzCMapL = ZZ_CMAP;

    int [] zzTransL = ZZ_TRANS;
    int [] zzRowMapL = ZZ_ROWMAP;
    int [] zzAttrL = ZZ_ATTRIBUTE;

    while (true) {
      zzMarkedPosL = zzMarkedPos;

      boolean zzR = false;
      for (zzCurrentPosL = zzStartRead; zzCurrentPosL < zzMarkedPosL;
                                                             zzCurrentPosL++) {
        switch (zzBufferL[zzCurrentPosL]) {
        case '\u000B':
        case '\u000C':
        case '\u0085':
        case '\u2028':
        case '\u2029':
          yyline++;
          yycolumn = 0;
          zzR = false;
          break;
        case '\r':
          yyline++;
          yycolumn = 0;
          zzR = true;
          break;
        case '\n':
          if (zzR)
            zzR = false;
          else {
            yyline++;
            yycolumn = 0;
          }
          break;
        default:
          zzR = false;
          yycolumn++;
        }
      }

      if (zzR) {
        // peek one character ahead if it is \n (if we have counted one line too much)
        boolean zzPeek;
        if (zzMarkedPosL < zzEndReadL)
          zzPeek = zzBufferL[zzMarkedPosL] == '\n';
        else if (zzAtEOF)
          zzPeek = false;
        else {
          boolean eof = zzRefill();
          zzEndReadL = zzEndRead;
          zzMarkedPosL = zzMarkedPos;
          zzBufferL = zzBuffer;
          if (eof) 
            zzPeek = false;
          else 
            zzPeek = zzBufferL[zzMarkedPosL] == '\n';
        }
        if (zzPeek) yyline--;
      }
      zzAction = -1;

      zzCurrentPosL = zzCurrentPos = zzStartRead = zzMarkedPosL;
  
      zzState = ZZ_LEXSTATE[zzLexicalState];


      zzForAction: {
        while (true) {
    
          if (zzCurrentPosL < zzEndReadL)
            zzInput = zzBufferL[zzCurrentPosL++];
          else if (zzAtEOF) {
            zzInput = YYEOF;
            break zzForAction;
          }
          else {
            // store back cached positions
            zzCurrentPos  = zzCurrentPosL;
            zzMarkedPos   = zzMarkedPosL;
            boolean eof = zzRefill();
            // get translated positions and possibly new buffer
            zzCurrentPosL  = zzCurrentPos;
            zzMarkedPosL   = zzMarkedPos;
            zzBufferL      = zzBuffer;
            zzEndReadL     = zzEndRead;
            if (eof) {
              zzInput = YYEOF;
              break zzForAction;
            }
            else {
              zzInput = zzBufferL[zzCurrentPosL++];
            }
          }
          int zzNext = zzTransL[ zzRowMapL[zzState] + zzCMapL[zzInput] ];
          if (zzNext == -1) break zzForAction;
          zzState = zzNext;

          int zzAttributes = zzAttrL[zzState];
          if ( (zzAttributes & 1) == 1 ) {
            zzAction = zzState;
            zzMarkedPosL = zzCurrentPosL;
            if ( (zzAttributes & 8) == 8 ) break zzForAction;
          }

        }
      }

      // store back cached position
      zzMarkedPos = zzMarkedPosL;

      switch (zzAction < 0 ? zzAction : ZZ_ACTION[zzAction]) {
        case 1: 
          { /* ignore */
          }
        case 58: break;
        case 40: 
          { return token(sym.NEW);
          }
        case 59: break;
        case 32: 
          { return token(sym.LAND);
          }
        case 60: break;
        case 3: 
          { return token(sym.RCBR);
          }
        case 61: break;
        case 11: 
          { return token(sym.MINUS);
          }
        case 62: break;
        case 35: 
          { string.append('\t');
          }
        case 63: break;
        case 39: 
          { yybegin(STATE_INLINE_COMMENT);
          }
        case 64: break;
        case 30: 
          { return token(sym.GTE);
          }
        case 65: break;
        case 24: 
          { throw new LexicalError("Unterminated string at end of line.", yyline);
          }
        case 66: break;
        case 51: 
          { return token(sym.LENGTH);
          }
        case 67: break;
        case 13: 
          { return token(sym.DOT);
          }
        case 68: break;
        case 12: 
          { return token(sym.COMMA);
          }
        case 69: break;
        case 16: 
          { return token(sym.PLUS);
          }
        case 70: break;
        case 7: 
          { return token(sym.RP);
          }
        case 71: break;
        case 55: 
          { return token(sym.EXTENDS);
          }
        case 72: break;
        case 34: 
          { return token(sym.LOR);
          }
        case 73: break;
        case 49: 
          { return token(sym.FALSE);
          }
        case 74: break;
        case 43: 
          { return token(sym.TRUE);
          }
        case 75: break;
        case 19: 
          { return token(sym.GT);
          }
        case 76: break;
        case 38: 
          { string.append('\\');
          }
        case 77: break;
        case 46: 
          { return token(sym.VOID);
          }
        case 78: break;
        case 20: 
          { return token(sym.LT);
          }
        case 79: break;
        case 47: 
          { return token(sym.CLASS);
          }
        case 80: break;
        case 42: 
          { return token(sym.ELSE);
          }
        case 81: break;
        case 26: 
          { yybegin(YYINITIAL);
          }
        case 82: break;
        case 15: 
          { return token(sym.ASSIGN);
          }
        case 83: break;
        case 4: 
          { return token(sym.LB);
          }
        case 84: break;
        case 54: 
          { return token(sym.RETURN);
          }
        case 85: break;
        case 41: 
          { return token(sym.INT);
          }
        case 86: break;
        case 21: 
          { return token(sym.LNEG);
          }
        case 87: break;
        case 44: 
          { return token(sym.THIS);
          }
        case 88: break;
        case 37: 
          { string.append('\"');
          }
        case 89: break;
        case 14: 
          { return token(sym.SEMI);
          }
        case 90: break;
        case 52: 
          { return token(sym.STATIC);
          }
        case 91: break;
        case 18: 
          { return token(sym.MOD);
          }
        case 92: break;
        case 10: 
          { return token(sym.INTEGER, Integer.parseInt(yytext()));
          }
        case 93: break;
        case 36: 
          { string.append('\n');
          }
        case 94: break;
        case 56: 
          { return token(sym.BOOLEAN);
          }
        case 95: break;
        case 28: 
          { return token(sym.IF);
          }
        case 96: break;
        case 23: 
          { string.append(yytext());
          }
        case 97: break;
        case 17: 
          { return token(sym.MULTIPLY);
          }
        case 98: break;
        case 6: 
          { return token(sym.LP);
          }
        case 99: break;
        case 31: 
          { return token(sym.LTE);
          }
        case 100: break;
        case 33: 
          { return token(sym.NEQUAL);
          }
        case 101: break;
        case 29: 
          { return token(sym.EQUAL);
          }
        case 102: break;
        case 50: 
          { return token(sym.BREAK);
          }
        case 103: break;
        case 45: 
          { return token(sym.NULL);
          }
        case 104: break;
        case 27: 
          { yybegin(STATE_COMMENT);
          }
        case 105: break;
        case 57: 
          { return token(sym.CONTINUE);
          }
        case 106: break;
        case 48: 
          { return token(sym.WHILE);
          }
        case 107: break;
        case 5: 
          { return token(sym.RB);
          }
        case 108: break;
        case 25: 
          { yybegin(YYINITIAL); return token(sym.QUOTE,string.toString());
          }
        case 109: break;
        case 22: 
          { string.setLength(0); yybegin(STATE_STRING);
          }
        case 110: break;
        case 2: 
          { return token(sym.LCBR);
          }
        case 111: break;
        case 8: 
          { return token(sym.ID);
          }
        case 112: break;
        case 53: 
          { return token(sym.STRING);
          }
        case 113: break;
        case 9: 
          { return token(sym.DIVIDE);
          }
        case 114: break;
        default: 
          if (zzInput == YYEOF && zzStartRead == zzCurrentPos) {
            zzAtEOF = true;
              { 	
	return new Token(sym.EOF,yyline,yycolumn);

 }
          } 
          else {
            zzScanError(ZZ_NO_MATCH);
          }
      }
    }
  }


}
